"""
Tests for scorpion.edge_testing (test_edges and regress_edges).

Compares Python output against R SCORPION reference data generated by
tests/generate_edge_test_data.R.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from scorpion.edge_testing import test_edges as _test_edges, regress_edges

DATA_DIR = Path(__file__).parent / "data"


@pytest.fixture(scope="module")
def networks_df():
    return pd.read_csv(DATA_DIR / "ref_networks_df.csv")


# ─── helpers ─────────────────────────────────────────────────────────────────

def _assert_frames_close(py_df, r_df, numeric_cols, atol=1e-6, rtol=1e-5):
    """Assert numeric columns of two DataFrames match within tolerance."""
    assert len(py_df) == len(r_df), f"Row count mismatch: {len(py_df)} vs {len(r_df)}"
    # Align by tf + target
    py_sorted = py_df.sort_values(["tf", "target"]).reset_index(drop=True)
    r_sorted = r_df.sort_values(["tf", "target"]).reset_index(drop=True)
    for col in numeric_cols:
        py_vals = py_sorted[col].to_numpy(dtype=float)
        r_vals = r_sorted[col].to_numpy(dtype=float)
        # Both NaN → ok; one NaN → fail
        both_nan = np.isnan(py_vals) & np.isnan(r_vals)
        either_nan = np.isnan(py_vals) | np.isnan(r_vals)
        mismatch_nan = either_nan & ~both_nan
        assert not mismatch_nan.any(), (
            f"Column '{col}': NaN mismatch at rows {np.where(mismatch_nan)[0]}"
        )
        valid = ~either_nan
        if valid.any():
            np.testing.assert_allclose(
                py_vals[valid], r_vals[valid],
                atol=atol, rtol=rtol,
                err_msg=f"Column '{col}' values differ",
            )


# ─── testEdges: single-sample ────────────────────────────────────────────────

class TestEdgesSingle:
    """Single-sample t-test (edges vs zero)."""

    def test_single_with_empirical_null(self, networks_df):
        """testEdges(single, moderateVariance=T, empiricalNull=T)"""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_single.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]

        py_res = _test_edges(
            networks_df, test_type="single", group1=tumor_cols,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanEdge", "tStatistic", "pValue", "pAdj"],
        )

    def test_single_no_empirical_null(self, networks_df):
        """testEdges(single, moderateVariance=T, empiricalNull=F)"""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_single_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]

        py_res = _test_edges(
            networks_df, test_type="single", group1=tumor_cols,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanEdge", "tStatistic", "pValue", "pAdj"],
        )


# ─── testEdges: two-sample ───────────────────────────────────────────────────

class TestEdgesTwoSample:
    """Two-sample Welch t-test."""

    def test_two_sample_with_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanGroup1", "meanGroup2", "diffMean", "cohensD",
             "log2FoldChange", "meanEdge", "tStatistic", "pValue", "pAdj"],
        )

    def test_two_sample_no_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanGroup1", "meanGroup2", "diffMean", "cohensD",
             "log2FoldChange", "meanEdge", "tStatistic", "pValue", "pAdj"],
        )

    def test_two_sample_no_moderation_no_empirical(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_nomod_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=False, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanGroup1", "meanGroup2", "diffMean", "cohensD",
             "log2FoldChange", "meanEdge", "tStatistic", "pValue", "pAdj"],
        )


# ─── testEdges: paired ──────────────────────────────────────────────────────

class TestEdgesPaired:
    """Paired t-test (matched donors)."""

    def test_paired_with_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_paired.csv")
        tumor_ordered = ["P1--T", "P2--T", "P3--T"]
        normal_ordered = ["P1--N", "P2--N", "P3--N"]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_ordered, group2=normal_ordered,
            paired=True,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanGroup1", "meanGroup2", "diffMean", "cohensD",
             "log2FoldChange", "meanEdge", "tStatistic", "pValue", "pAdj"],
        )

    def test_paired_no_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_paired_noemp.csv")
        tumor_ordered = ["P1--T", "P2--T", "P3--T"]
        normal_ordered = ["P1--N", "P2--N", "P3--N"]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_ordered, group2=normal_ordered,
            paired=True,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanGroup1", "meanGroup2", "diffMean", "cohensD",
             "log2FoldChange", "meanEdge", "tStatistic", "pValue", "pAdj"],
        )


# ─── regressEdges ────────────────────────────────────────────────────────────

class TestRegressEdges:
    """Linear regression across ordered conditions."""

    def test_regress_edges(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_regressEdges.csv")
        normal_cols = sorted([c for c in networks_df.columns if c.endswith("--N")])
        border_cols = sorted([c for c in networks_df.columns if c.endswith("--B")])
        tumor_cols = sorted([c for c in networks_df.columns if c.endswith("--T")])

        py_res = regress_edges(
            networks_df,
            ordered_groups={
                "Normal": normal_cols,
                "Border": border_cols,
                "Tumor": tumor_cols,
            },
        )

        _assert_frames_close(
            py_res, r_ref,
            ["slope", "intercept", "rSquared", "fStatistic",
             "pValue", "pAdj", "meanEdge",
             "meanNormal", "meanBorder", "meanTumor"],
        )


# ─── Input validation ────────────────────────────────────────────────────────

class TestInputValidation:

    def test_missing_group1(self, networks_df):
        with pytest.raises(ValueError, match="group1"):
            _test_edges(networks_df, test_type="single", group1=None)

    def test_missing_group2_two_sample(self, networks_df):
        with pytest.raises(ValueError, match="group2"):
            _test_edges(networks_df, test_type="two.sample",
                       group1=["P1--T"], group2=None)

    def test_paired_length_mismatch(self, networks_df):
        with pytest.raises(ValueError, match="same length"):
            _test_edges(networks_df, test_type="two.sample",
                       group1=["P1--T", "P2--T"], group2=["P1--N"],
                       paired=True)

    def test_regress_needs_two_conditions(self, networks_df):
        with pytest.raises(ValueError, match="at least 2"):
            regress_edges(networks_df, ordered_groups={"A": ["P1--T"]})
