"""
Tests for scorpion.edge_testing (test_edges, regress_edges and ma_edges).

Compares Python output against R SCORPION reference data generated by
tests/generate_edge_test_data.R.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from scorpion.edge_testing import (
    test_edges as _test_edges, regress_edges, ma_edges, _p_adjust,
)

DATA_DIR = Path(__file__).parent / "data"

TWO_SAMPLE_COLS = [
    "meanGroup1", "meanGroup2", "cohensD", "log2FoldChange",
    "meanEdge", "SE", "tStatistic", "pValue", "pAdj",
]
MA_COLS = [
    "k", "log2FoldChange", "SE", "ciLow", "ciHigh", "zStatistic",
    "pValue", "pAdj", "Q", "iSquared", "tauSquared",
]


@pytest.fixture(scope="module")
def networks_df():
    return pd.read_csv(DATA_DIR / "ref_networks_df.csv")


# ─── helpers ─────────────────────────────────────────────────────────────────

def _assert_frames_close(py_df, r_df, numeric_cols, atol=1e-6, rtol=1e-5):
    """Assert numeric columns of two DataFrames match within tolerance."""
    assert len(py_df) == len(r_df), f"Row count mismatch: {len(py_df)} vs {len(r_df)}"
    # Align by tf + target
    py_sorted = py_df.sort_values(["tf", "target"]).reset_index(drop=True)
    r_sorted = r_df.sort_values(["tf", "target"]).reset_index(drop=True)
    for col in numeric_cols:
        py_vals = py_sorted[col].to_numpy(dtype=float)
        r_vals = r_sorted[col].to_numpy(dtype=float)
        # Both NaN → ok; one NaN → fail
        both_nan = np.isnan(py_vals) & np.isnan(r_vals)
        either_nan = np.isnan(py_vals) | np.isnan(r_vals)
        mismatch_nan = either_nan & ~both_nan
        assert not mismatch_nan.any(), (
            f"Column '{col}': NaN mismatch at rows {np.where(mismatch_nan)[0]}"
        )
        valid = ~either_nan
        if valid.any():
            np.testing.assert_allclose(
                py_vals[valid], r_vals[valid],
                atol=atol, rtol=rtol,
                err_msg=f"Column '{col}' values differ",
            )


# ─── testEdges: single-sample ────────────────────────────────────────────────

class TestEdgesSingle:
    """Single-sample t-test (edges vs zero)."""

    def test_single_with_empirical_null(self, networks_df):
        """testEdges(single, moderateVariance=T, empiricalNull=T)"""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_single.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]

        py_res = _test_edges(
            networks_df, test_type="single", group1=tumor_cols,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanEdge", "SE", "tStatistic", "pValue", "pAdj"],
        )

    def test_single_no_empirical_null(self, networks_df):
        """testEdges(single, moderateVariance=T, empiricalNull=F)"""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_single_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]

        py_res = _test_edges(
            networks_df, test_type="single", group1=tumor_cols,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            ["meanEdge", "SE", "tStatistic", "pValue", "pAdj"],
        )


# ─── testEdges: two-sample ───────────────────────────────────────────────────

class TestEdgesTwoSample:
    """Two-sample Welch t-test."""

    def test_two_sample_with_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            TWO_SAMPLE_COLS,
        )

    def test_two_sample_no_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            TWO_SAMPLE_COLS,
        )

    def test_two_sample_no_moderation_no_empirical(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_nomod_noemp.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            moderate_variance=False, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            TWO_SAMPLE_COLS,
        )


# ─── testEdges: paired ──────────────────────────────────────────────────────

class TestEdgesPaired:
    """Paired t-test (matched donors)."""

    def test_paired_with_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_paired.csv")
        tumor_ordered = ["P1--T", "P2--T", "P3--T"]
        normal_ordered = ["P1--N", "P2--N", "P3--N"]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_ordered, group2=normal_ordered,
            paired=True,
            moderate_variance=True, empirical_null=True,
        )

        _assert_frames_close(
            py_res, r_ref,
            TWO_SAMPLE_COLS,
        )

    def test_paired_no_empirical_null(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_paired_noemp.csv")
        tumor_ordered = ["P1--T", "P2--T", "P3--T"]
        normal_ordered = ["P1--N", "P2--N", "P3--N"]

        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_ordered, group2=normal_ordered,
            paired=True,
            moderate_variance=True, empirical_null=False,
        )

        _assert_frames_close(
            py_res, r_ref,
            TWO_SAMPLE_COLS,
        )


class TestEdgesOptions:
    """Filtering, alternatives, p-value adjustment and parallel batches."""

    def test_column_order_matches_r(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]
        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
        )
        assert list(py_res.columns) == list(r_ref.columns)
        r_single = pd.read_csv(DATA_DIR / "ref_testEdges_single.csv")
        py_single = _test_edges(networks_df, test_type="single", group1=tumor_cols)
        assert list(py_single.columns) == list(r_single.columns)

    def test_filtered_greater_holm(self, networks_df):
        """minLog2FC=0.3, alternative='greater', padjustMethod='holm'"""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample_filtered.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]
        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            min_log2fc=0.3, alternative="greater", padjust_method="holm",
        )
        _assert_frames_close(py_res, r_ref, TWO_SAMPLE_COLS)

    def test_parallel_uses_global_s0(self, networks_df):
        """nCores=2, batchSize=70: s0 computed once over all edges."""
        r_ref = pd.read_csv(DATA_DIR / "ref_testEdges_two_sample_parallel.csv")
        tumor_cols = [c for c in networks_df.columns if c.endswith("--T")]
        normal_cols = [c for c in networks_df.columns if c.endswith("--N")]
        py_res = _test_edges(
            networks_df, test_type="two.sample",
            group1=tumor_cols, group2=normal_cols,
            min_log2fc=0.3, n_cores=2, batch_size=70,
        )
        _assert_frames_close(py_res, r_ref, TWO_SAMPLE_COLS)

    def test_p_adjust_matches_r(self):
        ref = pd.read_csv(DATA_DIR / "ref_p_adjust.csv")
        p = ref["p"].to_numpy(dtype=float)
        for method in ["holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "none"]:
            expected = ref[method].to_numpy(dtype=float)
            got = _p_adjust(p, method)
            np.testing.assert_array_equal(np.isnan(got), np.isnan(expected))
            ok = ~np.isnan(expected)
            np.testing.assert_allclose(got[ok], expected[ok], rtol=1e-10,
                                       err_msg=f"p.adjust method {method}")
        np.testing.assert_allclose(_p_adjust(p, "fdr"), _p_adjust(p, "BH"))

    def test_invalid_padjust_method(self, networks_df):
        with pytest.raises(ValueError, match="padjust_method"):
            _test_edges(networks_df, test_type="single", group1=["P1--T", "P2--T"],
                        padjust_method="nope")


# ─── regressEdges ────────────────────────────────────────────────────────────

class TestRegressEdges:
    """Linear regression across ordered conditions."""

    def test_regress_edges(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_regressEdges.csv")
        normal_cols = sorted([c for c in networks_df.columns if c.endswith("--N")])
        border_cols = sorted([c for c in networks_df.columns if c.endswith("--B")])
        tumor_cols = sorted([c for c in networks_df.columns if c.endswith("--T")])

        py_res = regress_edges(
            networks_df,
            ordered_groups={
                "Normal": normal_cols,
                "Border": border_cols,
                "Tumor": tumor_cols,
            },
        )

        _assert_frames_close(
            py_res, r_ref,
            ["slope", "intercept", "rSquared", "fStatistic",
             "pValue", "pAdj", "meanEdge",
             "meanNormal", "meanBorder", "meanTumor"],
        )


    def test_regress_edges_by_min_mean_edge(self, networks_df):
        r_ref = pd.read_csv(DATA_DIR / "ref_regressEdges_BY.csv")
        py_res = regress_edges(
            networks_df,
            ordered_groups={
                "Normal": sorted(c for c in networks_df.columns if c.endswith("--N")),
                "Border": sorted(c for c in networks_df.columns if c.endswith("--B")),
                "Tumor": sorted(c for c in networks_df.columns if c.endswith("--T")),
            },
            padjust_method="BY",
            min_mean_edge=0.1,
        )
        assert list(py_res.columns) == list(r_ref.columns)
        _assert_frames_close(
            py_res, r_ref,
            ["slope", "intercept", "rSquared", "fStatistic",
             "pValue", "pAdj", "meanEdge",
             "meanNormal", "meanBorder", "meanTumor"],
        )


# ─── maEdges ─────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def ma_studies():
    return [pd.read_csv(DATA_DIR / f"ma_study{i}.csv") for i in (1, 2, 3)]


class TestMaEdges:
    """Fixed/random-effects meta-analysis across studies."""

    @pytest.mark.parametrize("ref_file, kwargs", [
        ("ref_maEdges_random.csv", dict(method="random")),
        ("ref_maEdges_fixed.csv", dict(method="fixed")),
        ("ref_maEdges_random_k3_nomod.csv",
         dict(method="random", min_studies=3, moderate_variance=False)),
        ("ref_maEdges_fixed_s0.csv",
         dict(method="fixed", s0=0.05, padjust_method="bonferroni")),
    ])
    def test_ma_edges_matches_r(self, ma_studies, ref_file, kwargs):
        r_ref = pd.read_csv(DATA_DIR / ref_file)
        py_res = ma_edges(ma_studies, **kwargs)
        assert list(py_res.columns) == list(r_ref.columns)
        _assert_frames_close(py_res, r_ref, MA_COLS, atol=1e-8, rtol=1e-7)

    def test_ma_edges_accepts_dict(self, ma_studies):
        as_list = ma_edges(ma_studies)
        as_dict = ma_edges({f"s{i}": s for i, s in enumerate(ma_studies)})
        pd.testing.assert_frame_equal(as_list, as_dict)

    def test_ma_edges_needs_two_studies(self, ma_studies):
        with pytest.raises(ValueError, match="at least 2"):
            ma_edges(ma_studies[:1])

    def test_ma_edges_empty_result(self, ma_studies):
        res = ma_edges(ma_studies, min_studies=10)
        assert len(res) == 0
        assert list(res.columns) == ["tf", "target"] + MA_COLS


# ─── Input validation ────────────────────────────────────────────────────────

class TestInputValidation:

    def test_missing_group1(self, networks_df):
        with pytest.raises(ValueError, match="group1"):
            _test_edges(networks_df, test_type="single", group1=None)

    def test_missing_group2_two_sample(self, networks_df):
        with pytest.raises(ValueError, match="group2"):
            _test_edges(networks_df, test_type="two.sample",
                       group1=["P1--T"], group2=None)

    def test_paired_length_mismatch(self, networks_df):
        with pytest.raises(ValueError, match="same length"):
            _test_edges(networks_df, test_type="two.sample",
                       group1=["P1--T", "P2--T"], group2=["P1--N"],
                       paired=True)

    def test_regress_needs_two_conditions(self, networks_df):
        with pytest.raises(ValueError, match="at least 2"):
            regress_edges(networks_df, ordered_groups={"A": ["P1--T"]})
